### ISSUE TITLE
not able to receive output file from scrub file upload

### ISSUE THREAD

**Issue by AlliedDev** [blacklistalliance/scrubfile#1]
After uploading my csv file and setting the mapping criteria the following error message after submitting: 

Failed: TypeError: Failed to fetch

Here's the path I follow: Litigation Firewall/ scrub number file. 

I've tried different browsers and nothing works. I'm also not able to view the past files I had scrubbed. This worked continually for weeks and then stopped working. My colleague outside my network was able to do so but we've only tested it once. 

I also changed my download settings to verify where i'd like to save the file but I'm not asked after submitting. When working I see the file activate my download icon in the browser bar. 

![image](https://github.com/blacklistalliance/scrubfile/assets/170767450/c122bc34-33c0-4a5a-ab32-cb23c5ddca89)

**Comment by AlliedDev** [comment]
also, for files i have submitted and requested just the clean, how can I request the DNC and litigator list after the fact?

**Comment by ktmdan** [comment]
Please only report issues with the scrubfile application.  You are referencing the website and should use the chat on the website to get assistance.
